### ISSUE TITLE
No projects found.

### ISSUE THREAD

**Issue by AdnanHodzic** [justinmahar/github-projectv2-csv-exporter#17]
Hi,

I tried using [GitHub Project CSV Exporter (ProjectV2) via an URL](https://justinmahar.github.io/github-projectv2-csv-exporter/?path=/story/tools-github-project-exporter--exporter). However, after creating `GITHUB_EXPORTER_TOKEN` Github access token with necessary scopes I end up with "No projects found."

Any idea what's going on here?

![gitihub project csv exporter (no projects found)](https://github.com/justinmahar/github-projectv2-csv-exporter/assets/1041579/29e66088-f7ef-48a7-a95e-537e37a71fbc)

![github project csv exporter - exporter_token](https://github.com/justinmahar/github-projectv2-csv-exporter/assets/1041579/6758fb3a-d220-45e3-a941-eb7d25cd08a7)

Thanks!

**Comment by justinmahar** [comment]
This is super odd. Just tried my own token with my own personal projects and it's working.

Can you try creating a new test GitHub Project for one of your repos and see if it shows up? This project only works with newer v2 github projects, there's an older legacy format that's not supported by the API I'm using, that could be the other issue. See if new ones show up, and keep me posted!

**Comment by AdnanHodzic** [comment]
> This is super odd. Just tried my own token with my own personal projects and it's working.

Agreed ...

> Can you try creating a new test GitHub Project for one of your repos and see if it shows up? This tool only works with newer v2 github projects, there's an older legacy format that's not supported by the API I'm using, that could be the other issue. See if new ones show up, and keep me posted!

Nope, same problem. I created 2 new repositories yesterday, and they are also not showing up.

**Comment by justinmahar** [comment]
Just to be clear, it's not the repos themselves that will show up, but the projects assigned to them. You've created projects and assigned them to the repos? Not sure what to tell you if they're still not showing up.

**Comment by justinmahar** [comment]
Are you able to view the projects for the `microsoft` organization?

**Comment by AdnanHodzic** [comment]
> Are you able to view the projects for the `microsoft` organization?

Yes I can.

My bad, I misread this where I was expecting repositories and not projects. If I create a project and link to a repo then everything works as expected.

Thanks for your assistance and I apologize for the misunderstanding.
