### ISSUE TITLE
Cannot figure out how to use it

### ISSUE THREAD

**Issue by dlparker** [justinmahar/github-projectv2-csv-exporter#9]
I found this via googling for something that does this exporting, but I can't figure out how to use it. I am not a nodejs user so perhaps I don't know the magic words to run it after installing with npm. Can you update the instructions to tell people like me how to run an export via the local install, default options, whatever. Without that I don't see any way to use this without giving my access tokens to some web server you have up, which is a bad security decision.

**Comment by justinmahar** [comment]
Hey! So for this project I don't have my own web server up, it's just a static site hosted on GitHub Pages. The API key goes directly from your browser to Microsoft's API and back, not through a web server or anything like that.

That being said, if for security reasons you'd prefer to run and use the project locally, I totally get it. I've updated the instructions in the README with bash commands for cloning and running the project.

You can see the instructions here: https://github.com/justinmahar/github-projectv2-csv-exporter#locally

Hope this helps, let me know if you need any other help getting things running
